import test from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as path from "node:path";

test("extension wires story chat, memory, and metadata commands", async () => {
  const extPath = path.join(__dirname, "..", "src", "extension.ts");
  const pkgPath = path.join(__dirname, "..", "package.json");
  const ext = await fs.readFile(extPath, "utf8");
  const pkg = await fs.readFile(pkgPath, "utf8");
  assert.match(ext, /listStoryMemory/);
  assert.match(ext, /storyMemoryToContext/);
  assert.match(ext, /activeMemory/);
  assert.match(ext, /spanHint/);
  assert.match(ext, /selectedTextExcerpt/);
  assert.match(ext, /ed\.selection/);
  assert.match(ext, /manuscriptScope:\s*"selection"/);
  assert.match(ext, /saveStoryChatSessionSummary/);
  assert.match(ext, /storyChatLogStore/);
  assert.match(ext, /storyMemoryStore/);
  assert.match(ext, /Saved to story memory\./);
  assert.match(ext, /project\.yaml|outline-index\.json|chapter-status-index\.json/);
  assert.match(ext, /baseContextPaths|STORY_CHAT_BASE_CTX/);
  assert.match(ext, /kind:\s*"issue"|kind:\s*"chapter"|kind:\s*"thread"|kind:\s*"theme"/);
  assert.match(ext, /leanquill\.reviewChapter|prepareChapterReviewRun|getEnabledPersonasForProject/);
  assert.match(ext, /Choose how to run this review|One enabled persona…|All enabled personas|Select a persona|No enabled personas in this project/);
  assert.match(ext, /Session file and chat log started for this review/);
  assert.match(ext, /onDidSaveTextDocument|setTimeout|"Run"|"Dismiss"|leanquill\.runStoryIntelligenceUpdate/);
  assert.match(ext, /You saved a chapter\. Run a story intelligence pass on the full chapter\?/);
  assert.match(ext, /finalizeChapterReviewRun|leanquill\.saveChapterReviewResult|leanquill\.promoteSessionFindingToIssue/);
  assert.match(ext, /pathsForIssueChat/);
  assert.match(ext, /applyMetadataAction/);
  assert.match(ext, /Applied LeanQuill metadata action|LeanQuill blocked this metadata action/);
  assert.match(pkg, /leanquill\.startStoryChat/);
  assert.match(pkg, /leanquill\.saveStoryChatSummary/);
  assert.match(pkg, /onCommand:leanquill\.reviewChapter|LeanQuill: Run chapter review|leanquill\.reviewChapter/);
  assert.match(pkg, /Run chapter review/);
  assert.match(pkg, /webview\/context|leanquill\.outlineTree/);
  assert.match(pkg, /onCommand:leanquill\.runStoryIntelligenceUpdate|LeanQuill: Run story intelligence update for active chapter/);
  assert.match(pkg, /leanquill\.chatAboutIssue|"title": "Chat about this"/);
});
